/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente
 */
public class HubLivelli extends javax.swing.JFrame {
    NewJFrame f;
    /**
     * Creates new form HubLivelli
     */
    public HubLivelli(NewJFrame f) {
        this.f=f;
        initComponents();
        setSize(960,580); //pc normali
        setLocationRelativeTo(null); //centrare nello schermo
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LV1 = new javax.swing.JToggleButton();
        LV2 = new javax.swing.JToggleButton();
        LV3 = new javax.swing.JToggleButton();
        LV4 = new javax.swing.JToggleButton();
        TornaInizio = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        LV1.setBackground(new java.awt.Color(0, 102, 102));
        LV1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LV1.setText("LIVELLO 1");
        LV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV1ActionPerformed(evt);
            }
        });
        getContentPane().add(LV1);
        LV1.setBounds(212, 383, 120, 40);

        LV2.setBackground(new java.awt.Color(0, 102, 102));
        LV2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LV2.setText("LIVELLO 2");
        LV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV2ActionPerformed(evt);
            }
        });
        getContentPane().add(LV2);
        LV2.setBounds(352, 383, 120, 40);

        LV3.setBackground(new java.awt.Color(0, 102, 102));
        LV3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LV3.setText("LIVELLO 3");
        LV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV3ActionPerformed(evt);
            }
        });
        getContentPane().add(LV3);
        LV3.setBounds(492, 383, 120, 40);

        LV4.setBackground(new java.awt.Color(0, 102, 102));
        LV4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LV4.setText("LIVELLO 4");
        LV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV4ActionPerformed(evt);
            }
        });
        getContentPane().add(LV4);
        LV4.setBounds(630, 383, 120, 40);

        TornaInizio.setBackground(new java.awt.Color(0, 153, 51));
        TornaInizio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TornaInizio.setText("INDIETRO");
        TornaInizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TornaInizioActionPerformed(evt);
            }
        });
        getContentPane().add(TornaInizio);
        TornaInizio.setBounds(400, 450, 160, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 1 PROG FINALE.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 20, 215, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 2 PROG FINALE.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(255, 20, 215, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 3 PROG FINALE.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 20, 215, 330);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 4 PROG FINALE.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(725, 20, 215, 330);

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/sfondoHubLivelli.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 960, 540);

        setBounds(0, 0, 974, 547);
    }// </editor-fold>//GEN-END:initComponents

    private void LV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV2ActionPerformed
        Livello1 lv1 = new Livello1(f);
        setVisible(false);
    }//GEN-LAST:event_LV2ActionPerformed

    private void LV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV1ActionPerformed
        Livello0 lv0 = new Livello0(f);
        setVisible(false);
        
    }//GEN-LAST:event_LV1ActionPerformed

    private void TornaInizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TornaInizioActionPerformed
        NewJFrame NJ = new NewJFrame();
        setVisible(false);
    }//GEN-LAST:event_TornaInizioActionPerformed

    private void LV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV3ActionPerformed
        livello2 lv2 = new livello2(f);
        setVisible(false);
    }//GEN-LAST:event_LV3ActionPerformed

    private void LV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV4ActionPerformed
        Livello3 lv3 = new Livello3(f);
        setVisible(false);
    }//GEN-LAST:event_LV4ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LV1;
    private javax.swing.JToggleButton LV2;
    private javax.swing.JToggleButton LV3;
    private javax.swing.JToggleButton LV4;
    private javax.swing.JToggleButton TornaInizio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
