/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utente
 */
public class HubLivelli extends javax.swing.JFrame {
    NewJFrame f;
    /**
     * Creates new form HubLivelli
     */
    public HubLivelli(NewJFrame f) {
        this.f=f;
        initComponents();
        setSize(960,580); //pc normali
        setLocationRelativeTo(null); //centrare nello schermo
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LV1 = new javax.swing.JToggleButton();
        LV2 = new javax.swing.JToggleButton();
        LV3 = new javax.swing.JToggleButton();
        LV4 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        TornaInizio = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(960, 400));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 1 PROG FINALE.png"))); // NOI18N
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 232, 400);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 2 PROG FINALE.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(232, 0, 232, 400);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 3 PROG FINALE.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(464, 0, 232, 400);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/MAPPA 4 PROG FINALE.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(696, 0, 232, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(32, 0, 928, 400);

        jPanel2.setPreferredSize(new java.awt.Dimension(960, 70));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        LV1.setText("LIVELLO 1");
        LV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 316, 24, 0);
        jPanel2.add(LV1, gridBagConstraints);

        LV2.setText("LIVELLO 2");
        LV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV2ActionPerformed(evt);
            }
        });
        jPanel2.add(LV2, new java.awt.GridBagConstraints());

        LV3.setText("LIVELLO 3");
        LV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV3ActionPerformed(evt);
            }
        });
        jPanel2.add(LV3, new java.awt.GridBagConstraints());

        LV4.setText("LIVELLO 4");
        LV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LV4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 24, 316);
        jPanel2.add(LV4, gridBagConstraints);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 406, 960, 70);

        jPanel3.setLayout(null);

        TornaInizio.setText("INDIETRO");
        TornaInizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TornaInizioActionPerformed(evt);
            }
        });
        jPanel3.add(TornaInizio);
        TornaInizio.setBounds(435, 14, 81, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(6, 482, 951, 51);

        jPanel4.setPreferredSize(new java.awt.Dimension(20, 0));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(6, 6, 20, 394);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini livelli/sfondoHubLivelli.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-30, 0, 990, 540);

        setBounds(0, 0, 974, 547);
    }// </editor-fold>//GEN-END:initComponents

    private void LV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV2ActionPerformed
        Livello1 lv1 = new Livello1(f);
        setVisible(false);
    }//GEN-LAST:event_LV2ActionPerformed

    private void LV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV1ActionPerformed
        Livello0 lv0 = new Livello0(f);
        setVisible(false);
        
    }//GEN-LAST:event_LV1ActionPerformed

    private void TornaInizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TornaInizioActionPerformed
        NewJFrame NJ = new NewJFrame();
        setVisible(false);
    }//GEN-LAST:event_TornaInizioActionPerformed

    private void LV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV3ActionPerformed
        livello2 lv2 = new livello2(f);
        setVisible(false);
    }//GEN-LAST:event_LV3ActionPerformed

    private void LV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LV4ActionPerformed
        Livello3 lv3 = new Livello3(f);
        setVisible(false);
    }//GEN-LAST:event_LV4ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LV1;
    private javax.swing.JToggleButton LV2;
    private javax.swing.JToggleButton LV3;
    private javax.swing.JToggleButton LV4;
    private javax.swing.JToggleButton TornaInizio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
